version: "3.8"

services:
  nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: nacos-standalone
    environment:
      MODE: standalone
      PREFER_HOST_MODE: hostname
      SPRING_DATASOURCE_PLATFORM: derby
      NACOS_AUTH_ENABLE: "false"
    ports:
      - "8848:8848"
      - "9848:9848"
