server:
  port: 8088

spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.47:8848
        namespace: a475194c-967f-4d6d-b3c2-3bc626ef576d
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/stock/**
        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/credit/**
        - id: wms-service
          uri: lb://wms-service
          predicates:
            - Path=/wms/**

logging:
  level:
    org.springframework.cloud.gateway: debug
