server:
  port: 8082

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.47:8848
        namespace: a475194c-967f-4d6d-b3c2-3bc626ef576d
        username: nacos
        password: nacos
      sentinel:
        enabled: true

# 可选：让 Feign 使用 okhttp / 打印日志
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: full
